### ISSUE TITLE
glean.js files are generated as typescript, not js

### ISSUE THREAD

**Issue by manoelhortaribeiro** [mozilla-rally/rally-study-01#126]
After cloning the repo and following the instructions:

    npm install
    npm run dev

I get the following error:

    rollup v2.33.1
    bundles src/main.js → dist/background.js...
    (!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
    [!] Error: Could not resolve '../src/generated/event.js' from src/study.js
    Error: Could not resolve '../src/generated/event.js' from src/study.js
        at error (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:5252:30)
        at ModuleLoader.handleResolveId (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18393:24)
        at /Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18362:22
        at async Promise.all (index 6)
        at ModuleLoader.fetchStaticDependencies (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18360:34)
        at async Promise.all (index 0)
        at ModuleLoader.fetchModule (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18337:9)
        at async Promise.all (index 0)
        at ModuleLoader.fetchStaticDependencies (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18360:34)
        at async Promise.all (index 0)

And a chrome pop-up saying "Failed to load extension from: /Users/horta/PycharmProjects/rally-study-01. Could not load background script 'dist/background.js". Chrome eventually opens, but not sure it is working...

Weirdly, glean does not seem to generate the templates, isn't this necessary?  Also tried building the package:

    npm run package

Here, glean_parser created the metrics in `src/generated/*`, but still I get a (path related?) error:

    src/main.js → dist/background.js...
    (!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
    [!] Error: Could not resolve '../src/generated/page.js' from src/study.js
    Error: Could not resolve '../src/generated/page.js' from src/study.js
        at error (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:5252:30)
        at ModuleLoader.handleResolveId (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18393:24)
        at /Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18362:22
        at async Promise.all (index 4)
        at ModuleLoader.fetchStaticDependencies (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18360:34)
        at async Promise.all (index 0)
        at ModuleLoader.fetchModule (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18337:9)
        at async Promise.all (index 0)
        at ModuleLoader.fetchStaticDependencies (/Users/horta/PycharmProjects/rally-study-01/node_modules/rollup/dist/shared/rollup.js:18360:34)
        at async Promise.all (index 0)

**Comment by rhelmer** [comment]
@manoelhortaribeiro thanks for the report! It does like the problem is that Glean isn't generating files or isn't placing them in the expected place; I'll see if I can reproduce this. We simply run `npm run package` to produce the final build we push to the Add-ons store, so it's surprising to me that it wouldn't work for you.

Note that `rally-study-01` is slated to end soon, if you are interested in learning about Rally I'd suggest https://github.com/mozilla-rally/study-template/ as a more modern starting point (although it doesn't have Glean integrated quite yet, although [there's an issue for it](https://github.com/mozilla-rally/study-template/issues/99)).

Thanks!

**Comment by rhelmer** [comment]
OK I see looking at `package.json` that `npm run dev` does not cause run `npm run build:glean`. The other problem is that https://github.com/mozilla-rally/rally-study-01/blob/5d75ba1db8bd0ff7cb1cb38be1e017d732f16520/package.json#L8 configured Glean to generate typescript, but RS01's background script is still using JS.

I'll open a PR to address both of these.

**Comment by rhelmer** [comment]
Ugh OK and this is clearly failing on CircleCI for the main branch too 🤦 Thanks again for the report.
